### PR TITLE
Update tot.en.mdx

### PR DESCRIPTION
**Pull request by jieyilong**

### CODE REVIEW

**Comment by omarsar** [comment]
Hey @jieyilong. Thanks for the suggestions. Is there a significant difference between the papers?

**Comment by jieyilong** [comment]
Hi @omarsar thanks for the questions! At a high level, the main ideas of the two papers are similar, i.e. enhance LLM's capability for complex problem solving through a tree search via a multi-round conversation. One of the main difference, I think, is that Yao et al.'s paper leverages DFS/BFS/beam search, while the tree search strategy (i.e. when to backtrack and backtracking by how many levels, etc.) proposed in our paper is driven by a "ToT Controller" trained through reinforcement learning. DFS/BFS/Beam search are generic solution search strategies. In comparison, a ToT Controller trained through RL might be able to adapt to the problems better in theory (AlphaGo vs brute force search).

**Comment by omarsar** [comment]
@jieyilong To avoid any type of confusion, I think it makes sense to explain differences on the page without changing the explanation too much. If you can do that it would be great. Thanks.

**Comment by omarsar** [comment]
@jieyilong That's great! Thank you.

**Comment by jieyilong** [comment]
@omarsar thanks!

**Pull request merged**
