### PR TITLE
fix zh translation mistake in tips

### PR DESCRIPTION
**Pull request by BB-fat**

### CODE REVIEW

**Comment by omarsar** [comment]
@ZhengQinLai can you please check if these changes are okay?

**Comment by ZhengQinLai** [comment]
I'm sorry for not replying to your message in a timely manner. (T_T)
 I have been busy with some tasks on campus the past few days, and I will
double-check my translation.

**Review by ZhengQinLai — COMMENTED** [review]
yes, a mistake...

**Comment by BB-fat** [comment]
I found this bug still not fixed, can this pr be reopened? @omarsar

**Pull request closed without merging**
