### PR TITLE
guided cot (German translation)

### PR DESCRIPTION
**Pull request by behrends**

### CODE REVIEW

**Comment by omarsar** [comment]
@behrends please fix conflict. thanks

**Comment by behrends** [comment]
@omarsar Done

**Comment by omarsar** [comment]
@behrends conflicts still on this one. Pleas fix.

**Comment by behrends** [comment]
@omarsar Should be good now

**Comment by omarsar** [comment]
@behrends still have issues. please fix.

**Comment by behrends** [comment]
@omarsar fixed and checks passed

**Pull request merged**
