### PR TITLE
Add the basis of Arabic translation

### PR DESCRIPTION
**Pull request by hamzakat**
Hello @omarsar 

I started translating the guide to Arabic. This PR contains the basic files like the meta files and index page translated to see how things work! I followed the translation instructions you mentioned in previous translation PRs so all works reside in `ar-pages`.

For future work, I think we'll need to work on switching to RTL layout upon switching to Arabic language. Let me know about your thoughts on implementing this.

Thanks!

### CODE REVIEW

**Comment by hamzakat** [comment]
Hi @omarsar 
Just want to remind you about that (seems that my PR passed the checks!). Looking forward to hearing from you about RTL layout switching

**Comment by omarsar** [comment]
@hamzakat not sure about RTL. I will merge this and then reorganize the files manually. Thank you for all your efforts.

**Comment by omarsar** [comment]
@hamzakat The index page is live here: https://www.promptingguide.ai/ar
I suggest you translate the pages as soon as possible. And then move the translated pages from `ar-pages` to the corresponding folder inside `pages`. Please submit PRs so I can review them. The page is live and hopefully, you can translate them soon. Thanks a lot. I appreciate your effort.

**Comment by hamzakat** [comment]
Hello @Salah-Sal 

Happy to hear that you're interested in contribution! That will definitely accelerate publishing the Arabic translation.

1. I have started working on translating the files inside ‘ar-pages’ following the order of the sections. I have finished the first 2 major sections so far (Introduction - Techniques). Let me know which sections you are interested in so that we can collaborate effectively.

2. Great question. Actually, I didn't find a census glossary of the major terms in AI and LLM/NLP, even for *prompt engineering* term. I also discussed this issue in a Arabic translation tech community. I ended up adopting this:

> Prompt: أمر
> Prompts: أوامر
> Prompting: توجيه الأمر/الأوامر
> Prompt Engineering: هندسة الأوامر
> Zero-shot prompting: التوجيه بدون أمثلة
> Few-shot prompting: التوجيه ببضع أمثلة

I chose "توجيه" because it's commonly used in computing context and Microsoft translates "*Command Prompt*" to "*موجه الأوامر*" in Windows. Anyways, we can discuss this further if you like (maybe on Discord or any other communication channel). Additionally, I'm translating the examples when possible (e.g. put "س:" instead of  "Q:" in QnA prompts) and work on localizing them when necessary (e.g. some examples are designed specifically for English language. I'm trying to localize this without compromising the objective of the original example)

3. I think the plan now according to Omar is to (1) translate what's in `ar-pages`, (2) rename the file suffix to `.ar.mdx` once you finish, (3) and finally move that to the `pages` folder


Let me know what's your next step!

**Comment by omarsar** [comment]
Thanks for your interest @Salah-Sal. Please coordinate with @hamzakat as he has started some effort (explained above).

This would be an amazing addition since there is a lot of interest in this topic in the region. Thanks for your efforts. Let me know if you have any questions.

**Comment by Salah-Sal** [comment]
thats great there is a glossary being developed. would love to discuss it more on Discord. add me "iidavinciii"

**Pull request merged**
