### PR TITLE
Update: Chinese translation

### PR DESCRIPTION
**Pull request by RealTong**
- For a better reading experience on the Chinese internet, modify the spacing between Chinese and English characters.
- Update Chinese translation of the introduction section
- Update Chinese translation of the techniques section
- Add Chinese translation of reflexion section

### CODE REVIEW

**Comment by iFurySt** [comment]
Why don't you merge this PR? 🤔 @omarsar

**Comment by omarsar** [comment]
@iFurySt reviewing today and will merge later. thanks.

**Comment by omarsar** [comment]
@RealTong can you please fix the conflict?

**Comment by RealTong** [comment]
> @RealTong can you please fix the conflict?

Done.

**Pull request merged**
